Views
JacintaNgwu/Blog-App pull request #6
Opened 2023-04-20 11:07 UTC by JacintaNgwu

- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.

2023-04-20 11:41 UTC, AshakaE requested changes
Hi @JacintaNgwu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Your code base looks neat 👏 
- The use of Github flow ✅ 

## Required Changes ♻️

- [ ] Kindly ensure your `User` model is present, I'm unable to create a user 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 11:41 UTC, AshakaE commented on app/views/users/index.html.erb
> +</body>
- [ ] Kindly check that the right model is being called with the right type, I `.each` will only work on an array type 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/67957533/233354912-846d5f10-621d-449c-877b-db033a3ae2ef.png">

2023-04-21 16:16 UTC, VICTOR-CHUKWU requested changes
Hi @JacintaNgwu , 
## STATUS: CHANGES REQUIRED :recycle: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 16:16 UTC, VICTOR-CHUKWU commented on app/controllers/users_controller.rb
> +    @posts = @user.posts
- [ ] i get this error undefined method for posts  kindly fix, It worked when I replaced with ` @user = User.first` you can try other things
![Screenshot from 2023-04-21 17-00-56](https://user-images.githubusercontent.com/66097371/233682657-fcbbbbd6-4e3d-4bb3-ba57-cb37113db4df.png)

2023-04-21 16:16 UTC, VICTOR-CHUKWU commented on app/views/users/index.html.erb
> +</body>
- [ ] kindly make sure your design match the given wire frame
your design :point_down: 
![Screenshot from 2023-04-21 17-06-58](https://user-images.githubusercontent.com/66097371/233683750-5f1dad3b-5519-48f8-9b72-a8f41f8707c0.png)
given wire frame :point_down: 
![Screenshot from 2023-04-21 17-06-41](https://user-images.githubusercontent.com/66097371/233683819-d0d30ed0-1584-4b17-afc4-f173ab651cbe.png)

2023-04-21 16:16 UTC, VICTOR-CHUKWU commented on app/views/users/show.html.erb
> +</body>
- [ ] there is an error when I load user show page, kindly change `comment_counter` to `comments_counter` and also same for `like_counter` to `likes_counter`
![Screenshot from 2023-04-21 17-09-14](https://user-images.githubusercontent.com/66097371/233684465-c709badb-3274-4a85-a6b0-8b24ade771c1.png)
- [ ] also your design is not matching the wireframe, kindly follow design
your design :point_down: 
![Screenshot from 2023-04-21 17-12-12](https://user-images.githubusercontent.com/66097371/233684816-30b83858-e19d-4d41-a141-a42e36ab0a1e.png)

2023-04-21 16:16 UTC, VICTOR-CHUKWU commented on app/views/posts/index.html.erb
> +</body>
- [ ] there is an error in your post index, kindly fix this
![Screenshot from 2023-04-21 17-14-02](https://user-images.githubusercontent.com/66097371/233685124-26735c4d-e331-432a-bc49-2d768f46fc92.png)

2023-04-21 23:43 UTC, BenMukebo requested changes
Hi @JacintaNgwu, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._


You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 23:43 UTC, BenMukebo commented on app/views/users/index.html.erb
> +</div>
- [ ] Kindly as requested by the previous reviewer, the user index view page should match the given [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_root_users.png) However your design does not match the wireframe👇🏻 Kindly make sure that the index view page matches the given the user index view page should match the given [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_root_users.png).

Your Implementation | Original Design
:---:|:---:
![image](https://user-images.githubusercontent.com/79058364/233747379-d9acb96b-c89b-415a-abee-5d4deda33a1c.png) | ![image](https://user-images.githubusercontent.com/79058364/233747438-62834c84-a19a-490b-9201-2997b7a318cd.png)


- Do the same for your User show page.

![image](https://user-images.githubusercontent.com/79058364/233748112-c699af57-868d-4204-9c0d-520a26bb3a3c.png)

2023-04-21 23:43 UTC, BenMukebo commented on app/views/posts/index.html.erb
> + <%end%>
- [ ] You should pay more attention to the function as styling is nice to have the **See all Post** links open the user's post index as displayed on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png) However your design does not match the wireframe👇🏻 Kindly make sure that the index view page matches the given  [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png).

Your Implementation | Original Design
:---:|:---:
![image](https://user-images.githubusercontent.com/79058364/233747837-b214370e-0ee1-47bc-8144-56299fa1e09b.png) | ![image](https://user-images.githubusercontent.com/79058364/231671531-0b0de30c-f840-4c97-a525-15ae6cc6da35.png)
 
- Do the same for your Post show page.

![image](https://user-images.githubusercontent.com/79058364/233747955-1da783cd-6000-4350-ac6c-767ce938fceb.png)

2023-04-22 08:31 UTC, danmainah requested changes
Hi @JacintaNgwu , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 08:31 UTC, danmainah commented on app/views/users/show.html.erb
> +</button>
- [ ] @JacintaNgwu great work implementing the changes requested, however, you forgot to add the post counter title before the counter, the same case for the likes and comments counters 
![image](https://user-images.githubusercontent.com/61408860/233772895-25810e1b-5694-4706-9446-15a4ed93ea92.png)

2023-04-22 10:48 UTC, mwanawabangona approved these changes
Hi @JacintaNgwu 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested chnages!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 10:51 UTC, merged